// No "use client" since this is primarily a server component for global metadata and structure.
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";
import { AuthProvider } from "../app/context/AuthContext";
import { CartProvider } from "../app/context/CartContext";

// Google Fonts Declaration
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Inline Metadata */}
        <title>LUXORA</title>
        <meta name="description" content="Generated by create next app"></meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Auth & Cart Context Wrappers */}
        <AuthProvider>
          <CartProvider>
            <ClientProvider>{children}</ClientProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
