"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";
import { AuthProvider } from "../app/context/AuthContext";
import { CartProvider } from "../app/context/CartContext";
import { AnimatePresence, motion } from "framer-motion"; // Import framer-motion
import { usePathname } from "next/navigation"; // Import usePathname for route key

// Google Fonts Declaration
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current pathname for animation key

  return (
    <html lang="en">
      <head>
        {/* Inline Metadata */}
        <title>LUXORA</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Auth & Cart Context Wrappers */}
        <AuthProvider>
          <CartProvider>
            <ClientProvider>
              {/* AnimatePresence for page transitions */}
              <AnimatePresence mode="wait">
                <motion.div
                  key={pathname} // Key ensures animation triggers on route change
                  initial={{ opacity: 0 }} // Start with 0 opacity
                  animate={{ opacity: 1 }} // Fade in to full opacity
                  exit={{ opacity: 0, backgroundColor: "#000" }} // Fade to black on exit
                  transition={{ duration: 0.3 }} // 0.5s duration for smooth transition
                  style={{ minHeight: "100vh" }} // Ensure full height for background
                >
                  {children}
                </motion.div>
              </AnimatePresence>
            </ClientProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}