# Generated by Django 4.2.19 on 2025-03-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order'),
        ('product', '0003_order_orderitem'),
    ]

    operations = [
    ]
